comp4870assignment1/Controllers/MembersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ClassLibrary.Data;
using ClassLibrary.Models;
using Microsoft.AspNetCore.Authorization;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace assignment1.Controllers;

    [Authorize(Roles = "Admin")]
    public class MembersController : Controller
    {
        private readonly ApplicationDbContext _context;

        public MembersController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Members
        public async Task<IActionResult> Index()
        {
            return View(await _context.Members.ToListAsync());
        }

        // GET: Members/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var member = await _context.Members
                .FirstOrDefaultAsync(m => m.Id == id);
            if (member == null)
            {
                return NotFound();
            }

            return View(member);
        }

        // GET: Members/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Members/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("FirstName,LastName,Mobile,Street,City,PostalCode,Country,Created,Modified,CreatedBy,ModifiedBy,Id,UserName,NormalizedUserName,Email,NormalizedEmail,EmailConfirmed,PasswordHash,SecurityStamp,ConcurrencyStamp,PhoneNumber,PhoneNumberConfirmed,TwoFactorEnabled,LockoutEnd,LockoutEnabled,AccessFailedCount")] Member member)
        {
            if (ModelState.IsValid)
            {
                _context.Add(member);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(member);
        }

        // GET: Members/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var member = await _context.Members.FindAsync(id);
            if (member == null)
            {
                return NotFound();
            }
            return View(member);
        }

        // POST: Members/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("FirstName,LastName,Mobile,Street,City,PostalCode,Country,Created,Modified,CreatedBy,ModifiedBy,Id,UserName,NormalizedUserName,Email,NormalizedEmail,EmailConfirmed,PasswordHash,SecurityStamp,ConcurrencyStamp,PhoneNumber,PhoneNumberConfirmed,TwoFactorEnabled,LockoutEnd,LockoutEnabled,AccessFailedCount")] Member member)
        {   
            if (!await ValidateEmail(member))
            {
                return View(member);
            }
            var memberToUpdate = await _context.Members.FindAsync(id);
            if (memberToUpdate == null)
            {
                return NotFound();
            }
            
            if (ModelState.IsValid)
            {
                memberToUpdate.FirstName = member.FirstName;
                memberToUpdate.LastName = member.LastName;
                memberToUpdate.Mobile = member.Mobile;
                memberToUpdate.Street = member.Street;
                memberToUpdate.City = member.City;
                memberToUpdate.PostalCode = member.PostalCode;
                memberToUpdate.Country = member.Country;
                memberToUpdate.Modified = DateTime.Now;
                memberToUpdate.ModifiedBy = User.Identity!.Name;
                memberToUpdate.UserName = member.Email;
                memberToUpdate.Email = member.Email;
                memberToUpdate.NormalizedEmail = member.Email!.ToUpper();
                memberToUpdate.NormalizedUserName = member.Email.ToUpper();
                try
                {
                    _context.Update(memberToUpdate);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MemberExists(member.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            
            return View(member);
        }

        private async Task<bool> ValidateEmail(Member member)
        {
            if (string.IsNullOrEmpty(member.Email))
            {
                ModelState.AddModelError("Email", "Email is required.");
                return false;
            } else {
                // Check if email is already in use by another member, not including the current member
                var memberWithEmail = await _context.Members.FirstOrDefaultAsync(m => m.Email == member.Email && m.Id != member.Id);
                if (memberWithEmail != null)
                {
                    ModelState.AddModelError("Email", "Email is already in use.");
                    return false;
                }
            }

            return true;
        }

        // GET: Members/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var member = await _context.Members
                .FirstOrDefaultAsync(m => m.Id == id);
            if (member == null)
            {
                return NotFound();
            }

            return View(member);
        }

        // POST: Members/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var member = await _context.Members.FindAsync(id);
            if (member != null)
            {
                _context.Members.Remove(member);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MemberExists(string id)
        {
            return _context.Members.Any(e => e.Id == id);
        }
    }

comp4870assignment1/Controllers/TripsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ClassLibrary.Data;
using ClassLibrary.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;

namespace assignment1.Controllers;

[Authorize(Roles = "Admin, Owner, Passenger")]
public class TripsController : Controller
{
    private readonly ApplicationDbContext _context;

    private readonly UserManager<Member> _userManager;


    public TripsController(ApplicationDbContext context, UserManager<Member> userManager)
    {
        _context = context;
        _userManager = userManager;

    }

    public async Task<IActionResult> MyTrips()
    {
        string? userId = _userManager.GetUserId(User);
        var manifests = _context.Manifests
            .Where(m => m.MemberId == userId)
            .Include(m => m.Trip)
            .ThenInclude(t => t!.Vehicle)
            .Include(m => m.Trip)
            .ThenInclude(t => t!.Manifests)
            .OrderByDescending(m => m.Trip!.Date)
            .ToList();

        return await Task.FromResult(View(manifests));
    }
    
    // POST: Leave a Trip
    [HttpPost]
    public async Task<IActionResult> LeaveTrip(int tripId)
    {
        // Get the current user
        var userId = _userManager.GetUserId(User);

        // Find ManifestId with the same TripId
        var manifest = _context.Manifests.FirstOrDefault(m => m.TripId == tripId && m.MemberId == userId);
        if (manifest != null)
        {
            _context.Manifests.Remove(manifest);
            await _context.SaveChangesAsync();
        }

        return RedirectToAction(nameof(MyTrips));
    }

    // GET: Trips
    [Authorize(Roles = "Admin")]
    public async Task<IActionResult> Index()
    {
        string? userId = _userManager.GetUserId(User);
        var applicationDbContext = _context.Trips
            .Where(t => t.CreatedBy == userId) // Assuming there's a CreatedBy field or similar in your Trip model
            .Include(t => t.Vehicle);
        return View(await applicationDbContext.ToListAsync());
    }


    // GET: Trips/Details/5
    public async Task<IActionResult> Details(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var trip = await _context.Trips
            .Include(t => t.Vehicle)
            .Include(t => t.CreatedByMember)
            .Include(t => t.ModifiedByMember)
            .FirstOrDefaultAsync(m => m.TripId == id);
        if (trip == null)
        {
            return NotFound();
        }

        return View(trip);
    }

    // GET: Trips/Create
    [Authorize(Roles = "Admin, Owner")]
    public IActionResult Create()
    {
        // Is Owner only show your own vehicles
        if (User.IsInRole("Owner"))
        {
            string? userId = _userManager.GetUserId(User);
            ViewData["VehicleId"] = new SelectList(_context.Vehicles
                .Where(v => v.MemberId == userId)
                .Select(v => new { v.VehicleId, Description = "[" + v.VehicleId + "] " + v.Make + " " + v.Model }),
                "VehicleId", "Description");
            return View();
        } else {
            ViewData["VehicleId"] = new SelectList(_context.Vehicles
                .Select(v => new { v.VehicleId, Description = "[" + v.VehicleId + "] " + v.Make + " " + v.Model }),
                "VehicleId", "Description");
        }
        return View();
    }

    // POST: Trips/Create
    // To protect from overposting attacks, enable the specific properties you want to bind to.
    // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create([Bind("VehicleId,Date,Time,DestinationAddress,MeetingAddress,ManifestNote")] Trip trip, string? manifestNote)
    {
        if (ModelState.IsValid)
        {
            string? userId = _userManager.GetUserId(User);
            Trip newTrip = new()
            {
                VehicleId = trip.VehicleId,
                Date = trip.Date,
                Time = trip.Time,
                DestinationAddress = trip.DestinationAddress,
                MeetingAddress = trip.MeetingAddress,
                Created = DateTime.Now,
                Modified = DateTime.Now,
                CreatedBy = userId,
                ModifiedBy = userId
            };
            _context.Add(newTrip);
            await _context.SaveChangesAsync();

            //Add new Trip to Manifest
            Manifest newManifest = new()
            {
                ManifestId = _context.Manifests
                    .DefaultIfEmpty()
                    .Max(m => (int?)m!.ManifestId) + 1 ?? 1,
                MemberId = userId,
                TripId = newTrip.TripId,
                Notes = manifestNote,
                Created = DateTime.Now,
                Modified = DateTime.Now,
                CreatedBy = userId,
                ModifiedBy = userId
            };
            _context.Add(newManifest);
            await _context.SaveChangesAsync();
            // If they are owners send to MyTrips, otherwise send to Index
            if (User.IsInRole("Owner"))
            {
                return RedirectToAction(nameof(MyTrips));
            } else {
                return RedirectToAction(nameof(Index));
            }
        }
        ViewData["VehicleId"] = new SelectList(_context.Vehicles, "VehicleId", "VehicleId", trip.VehicleId);
        return View(trip);
    }

    // GET: Trips/Edit/5
    [Authorize(Roles = "Admin, Owner")]
    public async Task<IActionResult> Edit(int? tripId, int? vehicleId)
    {
        if (tripId == null || vehicleId == null)
        {
            return NotFound();
        }

        var trip = await _context.Trips
            .FirstOrDefaultAsync(m => m.TripId == tripId && m.VehicleId == vehicleId);
        if (trip == null)
        {
            return NotFound();
        }
        ViewData["VehicleId"] = new SelectList(_context.Vehicles
            .Select(v => new { v.VehicleId, Description = v.Make + " " + v.Model }),
            "VehicleId", "Description");
        return View(trip);
    }

    // POST: Trips/Edit/5
    // To protect from overposting attacks, enable the specific properties you want to bind to.
    // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(int tripId, int vehicleId, [Bind("TripId,VehicleId,Date,Time,DestinationAddress,MeetingAddress,Created,Modified,CreatedBy,ModifiedBy")] Trip trip)
    {
        if (tripId != trip.TripId || vehicleId != trip.VehicleId)
        {
            return NotFound();
        }

        if (ModelState.IsValid)
        {
            try
            {
                _context.Update(trip);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!TripExists(trip.TripId))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            // If they are owners send to MyTrips, otherwise send to Index
            if (User.IsInRole("Owner"))
            {
                return RedirectToAction(nameof(MyTrips));
            } else {
                return RedirectToAction(nameof(Index));
            }
        }
        ViewData["VehicleId"] = new SelectList(_context.Vehicles, "VehicleId", "VehicleId", trip.VehicleId);
        return View(trip);
    }

    // GET: Trips/Delete/5
    [Authorize(Roles = "Admin, Owner")]
    public async Task<IActionResult> Delete(int? tripId)
    {
        if (tripId == null)
        {
            return NotFound();
        }

        var trip = await _context.Trips
            .FirstOrDefaultAsync(m => m.TripId == tripId);
        if (trip == null)
        {
            return NotFound();
        }

        return View(trip);
    }

    // POST: Trips/Delete/5
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed(int tripId)
    {
        var trip = await _context.Trips
            .FirstOrDefaultAsync(m => m.TripId == tripId);
        if (trip != null)
        {
            _context.Trips.Remove(trip);
            await _context.SaveChangesAsync();
        }
        // If they are owners send to MyTrips, otherwise send to Index
        if (User.IsInRole("Owner"))
        {
            return RedirectToAction(nameof(MyTrips));
        } else {
            return RedirectToAction(nameof(Index));
        }
    }

    private bool TripExists(int tripId)
    {
        return _context.Trips.Any(e => e.TripId == tripId);
    }

    // POST: Trips/RateTrip
    [HttpPost]
    public async Task<IActionResult> MyTrips(int manifestId, int rating)
    {
        // Get the current user
        var userId = _userManager.GetUserId(User);

        // Print out the userId, manifestId, and rating
        Console.WriteLine("userId: " + userId);
        Console.WriteLine("manifestId: " + manifestId);
        Console.WriteLine("rating: " + rating);

        // Find ManifestId with the same TripId
        var manifest = _context.Manifests.FirstOrDefault(m => m.ManifestId == manifestId && m.MemberId == userId);
        if (manifest != null)
        {
            manifest.Rating = rating;
            await _context.SaveChangesAsync();
        }

        return RedirectToAction(nameof(MyTrips));
    }
}

comp4870assignment1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - assignment1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/assignment1.styles.css" asp-append-version="true" />
    @RenderSection("Styles", required: false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/images/logo.png" alt="logo" style="width: 50px; height: 50px;" />
                    <span>Car Pool Go</span>
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            @if (User.IsInRole("Admin") || User.IsInRole("Owner") || User.IsInRole("Passenger")) {
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            }
                        </li>
                        <li class="nav-item">
                            @if (User.IsInRole("Admin")) {
                                <a class="nav-link text-dark" asp-area="" asp-controller="Manifests" asp-action="Index">Manifests</a>
                            }
                        </li>
                        <li class="nav-item">
                            @if (User.IsInRole("Owner")) {
                                <a class="nav-link text-dark" asp-area="" asp-controller="Manifests" asp-action="TripPdf">Manifests</a>
                            }
                        </li>
                        <li class="nav-item">
                            @if (User.IsInRole("Admin")) {
                                <a class="nav-link text-dark" asp-area="" asp-controller="Members" asp-action="Index">Members</a>
                            }
                        </li>
                        <li class="nav-item">
                            @if (User.IsInRole("Admin")) {
                                <a class="nav-link text-dark" asp-area="" asp-controller="Trips" asp-action="Index">Trips</a>
                            }
                        </li>
                        <li class="nav-item">
                            @if (User.IsInRole("Passenger") || User.IsInRole("Owner")) {
                                <a class="nav-link text-dark" asp-area="" asp-controller="Trips" asp-action="MyTrips">Trips</a>
                            }
                        </li>
                        <li class="nav-item">
                            @if (User.IsInRole("Admin") || User.IsInRole("Owner")) {
                                <a class="nav-link text-dark" asp-area="" asp-controller="Vehicles" asp-action="Index">Vehicles</a>
                            }
                        </li>
                        <li class="nav-item">
                            @if (User.IsInRole("Admin")) {
                                <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Index">Admin</a>
                            }
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Car Pool Go - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            <p>Ozan Yurtisigi, Darren Luck, Lester Shun, Khanh Linh Nguyen</p>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>