comp4870assignment1/Controllers/ManifestsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ClassLibrary.Data;
using ClassLibrary.Models;
using Microsoft.AspNetCore.Authorization;
using iText.Kernel.Colors;
using iText.Kernel.Geom;
using iText.Kernel.Pdf;
using iText.Kernel.Pdf.Canvas.Draw;
using iText.Layout;
using iText.Layout.Element;
using iText.Layout.Properties;
using System.Security.Claims;
using iText.IO.Image;

namespace assignment1.Controllers;

[Authorize(Roles = "Admin, Owner")]
public class ManifestsController : Controller
{
    private readonly ApplicationDbContext _context;
    private readonly IWebHostEnvironment _env;

    public ManifestsController(ApplicationDbContext context, IWebHostEnvironment env)
    {
        _context = context;
        _env = env;
    }

    public async Task<IActionResult> GeneratePDFReport()
    {
        var ms = new MemoryStream();

        // Create a PdfWriter instance directing it to write to the MemoryStream.
        var writer = new PdfWriter(ms);
        var pdfDoc = new PdfDocument(writer);
        var document = new Document(pdfDoc, PageSize.A4);
        writer.SetCloseStream(false);

        // Add logo
        string logoPath = System.IO.Path.Combine(_env.WebRootPath, "images/logo.png");
        ImageData logoData = ImageDataFactory.Create(logoPath);
        Image logo = new Image(logoData).SetWidth(100).SetHeight(100);
        document.Add(logo);

        // Header
        Paragraph header = new Paragraph("Manifest Report")
            .SetTextAlignment(TextAlignment.CENTER)
            .SetFontSize(20);
        document.Add(header);

        // Sub-header
        Paragraph subheader = new Paragraph($"Generated on: {DateTime.Now.ToShortDateString()}")
            .SetTextAlignment(TextAlignment.CENTER)
            .SetFontSize(15);
        document.Add(subheader);

        // Line separator and an empty space
        document.Add(new LineSeparator(new SolidLine())).Add(new Paragraph("\n"));

        // Manifest Data Table
        document.Add(await GetManifestPdfTable());

        // Closing the document
        document.Close();

        // Reset the MemoryStream position to the beginning.
        ms.Position = 0;

        // Return the stream as a PDF file.
        return new FileStreamResult(ms, "application/pdf")
        {
            FileDownloadName = "ManifestReport.pdf"
        };
    }


    private async Task<Table> GetManifestPdfTable()
    {
        Table table = new Table(UnitValue.CreatePercentArray(new float[] { 3, 3, 3, 3, 4 })).UseAllAvailableWidth();

        // Adding column headers
        string[] headers = { "Manifest ID", "Member", "Destination Address", "Meeting Address", "Notes" };
        foreach (var header in headers)
        {
            table.AddHeaderCell(new Cell().Add(new Paragraph(header).SetBold()));
        }

        // Fetching Manifest data
        var manifests = await _context.Manifests
            .Include(m => m.Member)
            .Include(m => m.Trip)
            .ToListAsync();

        // Adding data to the table
        foreach (var manifest in manifests)
        {
            table.AddCell(new Cell().Add(new Paragraph(manifest.ManifestId.ToString())));
            table.AddCell(new Cell().Add(new Paragraph(manifest.Member?.UserName ?? "N/A")));
            table.AddCell(new Cell().Add(new Paragraph(manifest.Trip?.DestinationAddress ?? "N/A")));
            table.AddCell(new Cell().Add(new Paragraph(manifest.Trip?.MeetingAddress ?? "N/A")));
            table.AddCell(new Cell().Add(new Paragraph(manifest.Notes ?? "No notes")));
        }

        return table;
    }

    public async Task<IActionResult> TripPdf()
    {
        // Retrieve the ID of the current logged-in user
        var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

        IQueryable<Manifest> query;

        // Check if the current user is an admin
        if (User.IsInRole("Admin"))
        {
            // Admins get to see all manifests
            query = _context.Manifests.Include(m => m.Member)
                .Include(m => m.Member)
                .Include(m => m.Trip)
                .ThenInclude(t => t!.Vehicle)
                .Include(m => m.Trip)
                .ThenInclude(t => t!.Manifests)
                .OrderByDescending(m => m.Trip!.Date);
                ;
        }
        else
        {
            // Regular users see only their manifests
            query = _context.Manifests
                .Include(m => m.Member)
                .Include(m => m.Trip)
                .ThenInclude(t => t!.Vehicle)
                .Include(m => m.Trip)
                .ThenInclude(t => t!.Manifests)
                .Where(m => m.MemberId == userId)
                .OrderByDescending(m => m.Trip!.Date);
        }

        var manifests = await query.ToListAsync();

        // Pass the list of manifests to the view
        return View(manifests);
    }


    public async Task<IActionResult> GenerateTripPDFReport(int manifestId)
    {
        var ms = new MemoryStream();

        // Create a PdfWriter instance directing it to write to the MemoryStream.
        var writer = new PdfWriter(ms);
        var pdfDoc = new PdfDocument(writer);
        var document = new Document(pdfDoc, PageSize.A4);
        writer.SetCloseStream(false);

        // Retrieve the Manifest including its Trip
        var manifest = await _context.Manifests
            .Include(m => m.Trip)
            .ThenInclude(t => t!.Vehicle) // Assuming you want vehicle details as well
            .Include(m => m!.Member)
            .Where(m => m.ManifestId == manifestId)
            .ToListAsync();

        if (manifest == null)
        {
            return NotFound();
        }

        // Add logo
        string logoPath = System.IO.Path.Combine(_env.WebRootPath, "images/logo.png");
        ImageData logoData = ImageDataFactory.Create(logoPath);
        Image logo = new Image(logoData).SetWidth(100).SetHeight(100);
        document.Add(logo);

        // Header
        Paragraph header = new Paragraph("Trip Report")
            .SetTextAlignment(TextAlignment.CENTER)
            .SetFontSize(20);
        document.Add(header);

        // Sub-header
        Paragraph subheader = new Paragraph($"Generated on: {DateTime.Now.ToShortDateString()}")
            .SetTextAlignment(TextAlignment.CENTER)
            .SetFontSize(15);
        document.Add(subheader);

        document.Add(new LineSeparator(new SolidLine())).Add(new Paragraph("\n"));

        // Adding Trip Details
        document.Add(new Paragraph($"Trip ID: {manifest[0].TripId}"));
        document.Add(new Paragraph($"Destination Address: {manifest[0].Trip?.DestinationAddress ?? "N/A"}"));
        document.Add(new Paragraph($"Meeting Address: {manifest[0].Trip?.MeetingAddress ?? "N/A"}"));
        document.Add(new Paragraph($"Date: {manifest[0].Trip?.Date?.ToString("d") ?? "N/A"}"));
        document.Add(new Paragraph($"Time: {manifest[0].Trip?.Time?.ToString("t") ?? "N/A"}"));

        // Optionally, add vehicle details and any other relevant information
        document.Add(new LineSeparator(new SolidLine())).Add(new Paragraph("\n"));
        document.Add(new Paragraph("Passengers")
            .SetTextAlignment(TextAlignment.CENTER)
            .SetFontSize(15));
        for (int i = 0; i < manifest.Count; i++)
        {
            document.Add(new Paragraph($"Name: {manifest[i].Member?.FirstName} {manifest[i].Member?.LastName ?? "N/A"}")).SetFontSize(10);
            document.Add(new Paragraph($"Email: {manifest[i].Member?.Email ?? "N/A"}")).SetFontSize(10);
            document.Add(new LineSeparator(new DashedLine())).Add(new Paragraph("\n"));
        }

        // Closing the document
        document.Close();

        // Reset the MemoryStream position to the beginning.
        ms.Position = 0;

        // Return the stream as a PDF file
        return new FileStreamResult(ms, "application/pdf")
        {
            FileDownloadName = $"TripReport_{manifest[0].TripId}.pdf"
        };
    }

    // GET: Manifests
    [Authorize(Roles = "Admin")]
    public async Task<IActionResult> Index()
    {
        var applicationDbContext = _context.Manifests
            .Include(m => m.Member)
            .Include(m => m.Trip);
        return View(await applicationDbContext.ToListAsync());
    }

    // GET: Manifests/Details/5
    public async Task<IActionResult> Details(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var manifest = await _context.Manifests
            .Include(m => m.CreatedByMember)
            .Include(m => m.ModifiedByMember)
            .Include(m => m.Member)
            .Include(m => m.Trip)
            .FirstOrDefaultAsync(m => m.ManifestId == id);
        if (manifest == null)
        {
            return NotFound();
        }

        return View(manifest);
    }

    // GET: Manifests/Edit/5
    public async Task<IActionResult> Edit(int? manifestId, string? memberId)
    {
        if (manifestId == null || memberId == null)
        {
            return NotFound();
        }

        var manifest = await _context.Manifests
            .FirstOrDefaultAsync(m => m.ManifestId == manifestId && m.MemberId == memberId);
        if (manifest == null)
        {
            return NotFound();
        }
        ViewData["MemberId"] = new SelectList(_context.Members, "Id", "Id", manifest.MemberId);
        ViewData["TripId"] = new SelectList(_context.Trips
                .Select(t => new { t.TripId, Description = "[" + t.TripId + "] Destination: " + t.DestinationAddress }),
                "TripId", "Description");
        return View(manifest);
    }

    // POST: Manifests/Edit/5
    // To protect from overposting attacks, enable the specific properties you want to bind to.

comp4870assignment1/Views/Manifests/Delete.cshtml
@model ClassLibrary.Models.Manifest

@{
    ViewData["Title"] = "Delete Manifest";
}

<component type="typeof(DeleteManifest)" render-mode="ServerPrerendered" param-ManifestId="@Model.ManifestId" param-MemberId="@Model.MemberId" />

comp4870assignment1/Views/Manifests/Details.cshtml
@model ClassLibrary.Models.Manifest

@{
    ViewData["Title"] = "Manifest Details";
}

<h1>@ViewData["Title"]</h1>

<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            Member ID
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Member!.Id)
        </dd>
        <dt class = "col-sm-2">
            Member
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Member!.UserName)
        </dd>
        <dt class = "col-sm-2">
            Trip ID
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Trip!.TripId)
        </dd>
        <dt class = "col-sm-2">
            Trip Meeting Address
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Trip!.MeetingAddress)
        </dd>
        <dt class = "col-sm-2">
            Trip Destination Address
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Trip!.DestinationAddress)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Notes)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Notes)
        </dd>
        <hr/>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Created)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Created)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Modified)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Modified)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedByMember!.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ModifiedBy)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ModifiedByMember!.Email)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Index" class="btn btn-secondary">Back to List</a>
</div>

comp4870assignment1/Views/Manifests/Edit.cshtml
@model ClassLibrary.Models.Manifest

@{
    ViewData["Title"] = "Edit Manifest";
}

<h1>@ViewData["Title"]</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ManifestId" />
            <input type="hidden" asp-for="MemberId" />
            <div class="form-group">
                <label asp-for="TripId" class="control-label">Trip</label>
                <select asp-for="TripId" class="form-control" asp-items="ViewBag.TripId"></select>
                <span asp-validation-for="TripId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Notes" class="control-label"></label>
                <input asp-for="Notes" class="form-control" />
                <span asp-validation-for="Notes" class="text-danger"></span>
            </div>
            <br/>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
                <a asp-action="Index" class="btn btn-secondary">Back to List</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

comp4870assignment1/Views/Manifests/GeneratePDFReport.cshtml
<h3>GeneratePDFReport</h3>

@{

}

comp4870assignment1/Views/Manifests/Index.cshtml
@model IEnumerable<ClassLibrary.Models.Manifest>
@using assignment1.Components

@{
    ViewData["Title"] = "All Manifests";
}

<component type="typeof(Manifests)" render-mode="ServerPrerendered" />

@if (User.IsInRole("Admin")) {
    <a asp-action="GeneratePDFReport" asp-controller="Manifests" class="btn btn-primary">Generate All Manifest Report</a>
}

<a asp-action="TripPdf" asp-controller="Manifests" class="btn btn-secondary">Generate Trip Report</a>

comp4870assignment1/Views/Manifests/TripPdf.cshtml
@model IEnumerable<ClassLibrary.Models.Manifest>

@{
    ViewData["Title"] = "Export Trip Manifests";
}

<h3>Manifests List</h3>

<table class="table">
    <thead>
        <tr>
            <th>Driver</th>
            <th>Passengers</th>
            <th>Date</th>
            <th>Meeting Address</th>
            <th>Trip Destination</th>
            <th>Notes</th>
            <th>Generate a trip report for this manifest</th>
        </tr>
    </thead>
    <tbody>
    @foreach (var manifest in Model)
    {
        <tr>
            <td>@manifest.Member?.Email</td>
            <td>@manifest.Trip?.Manifests?.Count / @manifest.Trip?.Vehicle?.NumberOfSeats</td>
            <td>@manifest.Trip?.Date @manifest.Trip?.Time</td>
            <td>@manifest.Trip?.MeetingAddress</td>
            <td>@manifest.Trip?.DestinationAddress</td>
            <td>@manifest.Notes</td>
            <td><a href="@Url.Action("GenerateTripPDFReport", new { manifestId = manifest.ManifestId })">Generate Trip Report</a></td>
        </tr>
    }
    </tbody>
</table>